version: "2.2"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: tyollisyyspalvelut_es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
