version: '2.2'
services:
  es:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tyollisyyspalvelut_es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - stonehenge-network
networks:
  elastic:
    driver: bridge
