<?php

/**
 * @file
 * Hooks for Työllisyyspalvelut Common module.
 */

use Drupal\editor\Entity\Editor;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityForm;
use Drupal\Core\Url;

/**
 * @param array $css
 * @param Editor $editor
 */
function tyollisyyspalvelut_common_ckeditor_css_alter(array &$css, Editor $editor) {
  $css[] = drupal_get_path('module', 'tyollisyyspalvelut_common') . '/ckeditor.css';
}

/**
 * Implements hook_form_alter().
 */
function tyollisyyspalvelut_common_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  // Hide field from HDBT theme we don't want to use.
  $form['color_palette']['#access'] = FALSE;

  // Hide preview button for now.
  $form['actions']['preview']['#access'] = FALSE;

  // Custom redirect after save.
  $form['actions']['submit']['#submit'][] = 'redirectFunction';
}

/**
 * Redirect to node view page after save.
 */
function redirectFunction(array &$form, FormStateInterface $form_state) {
  /** @var \Drupal\Core\Entity\EntityForm $form_object */
  $form_object = $form_state->getFormObject();
  if ($form_object instanceof EntityForm) {
    $entity = $form_object->getEntity();

    // Remove destination query string from request.
    \Drupal::request()->query->remove('destination');
    $url = Url::fromRoute('entity.node.canonical', ['node' => $entity->id()]);
    $form_state->setRedirectUrl($url);
    return;
  }
}
