features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
favicon:
  use_default: 1
enable_darkmode: 0
preset_accent_color: null
accent_color: ''
preset_focus_color: gin
focus_color: ''
high_contrast_mode: 0
show_user_theme_settings: 0
classic_toolbar: horizontal
icon_default: 1
icon_upload: ''
