_core:
  default_config_hash: MC-TKIpL-pL-xdDFY5NSz8A09wulfwE5RmtauLkC1-k
path_to_json: /themes/custom/hdbt_subtheme/src/icons/editor-selectable-icons.json
path_to_sprite: /themes/contrib/hdbt/dist/icons/sprite.svg
langcode: fi
